### ISSUE TITLE
About the paper

### ISSUE THREAD

**Issue by kaiw7** [haoyi-duan/DG-SCT#1]
Hi, could I know when you will release your paper? Many thanks

**Comment by haoyi-duan** [comment]
Hi, we appreciate your interest in our paper. Our paper will be released after the conference concludes. Thank you for your patience!

**Comment by kaiw7** [comment]
> Hi, we appreciate your interest in our paper. Our paper will be released after the conference concludes. Thank you for your patience!

Hi, thanks for your quick reply. Could I know the approximate time?

**Comment by haoyi-duan** [comment]
Hello, probably in early December!

**Comment by kaiw7** [comment]
> Hello, probably in early December!

Many thanks. Could I know how many trainable parameters are involved in your proposed models evaluated on different audio-visual tasks? In addition, what is HTS-AT used in audio encoder?

**Comment by haoyi-duan** [comment]
We use 43.6M trainable parameters in AVE task. In general, our approach utilizes more trainable parameters. However, the increase of trainable parameters primarily arises from the inclusion of a two-dimensional convolution kernel and a linear projection. These additions ensure consistency of dimensions between the audio and visual prompts. In other words, the increase in parameter count from our approach mainly results from addressing the inconsistency in dimensions between the audio and visual encoders. For your second question, HTS-AT (https://arxiv.org/abs/2202.00874) is a transformer-based audio encoder. I hope my answer will be helpful to you, thank you!

**Comment by kaiw7** [comment]
> We use 43.6M trainable parameters in AVE task. In general, our approach utilizes more trainable parameters. However, the increase of trainable parameters primarily arises from the inclusion of a two-dimensional convolution kernel and a linear projection. These additions ensure consistency of dimensions between the audio and visual prompts. In other words, the increase in parameter count from our approach mainly results from addressing the inconsistency in dimensions between the audio and visual encoders. For your second question, HTS-AT (https://arxiv.org/abs/2202.00874) is a transformer-based audio encoder. I hope my answer will be helpful to you, thank you!

Thank you very much for your clear explanation. I have another question about AVQA results. From the table, I notived that the reuslts of LAVisH (using shared Swin-V2-L) are different from the ones from the original paper. Could I know what is the difference in the implementation?

**Comment by haoyi-duan** [comment]
Actually, there is no difference. our results are obtained by running the official LAVisH code on our machine. It is likely that the original paper evaluated accuracy using the validation dataset, while we employed the test dataset, following the methodology outlined in the original MUSIC-AVQA paper (https://openaccess.thecvf.com/content/CVPR2022/papers/Li_Learning_To_Answer_Questions_in_Dynamic_Audio-Visual_Scenarios_CVPR_2022_paper.pdf).
