### ISSUE TITLE
About citation

### ISSUE THREAD

**Issue by kaiw7** [haoyi-duan/DG-SCT#2]
Hi, do you plan to make your paper public in arxiv so that others can cite it?

**Comment by haoyi-duan** [comment]
Hi, already submitted to arxiv! I'll let you know when it is available!

**Comment by haoyi-duan** [comment]
Hi, our paper is now available https://arxiv.org/abs/2311.05152

**Comment by kaiw7** [comment]
> Hi, our paper is now available https://arxiv.org/abs/2311.05152

Hi, thank you very much for your informing.
