### ISSUE TITLE
Access denied for downloading pre-trained checkpoints

### ISSUE THREAD

**Issue by fisheggg** [haoyi-duan/DG-SCT#4]
Hi,

Thanks for the work! I'm trying to download the pre-trained checkpoints for the backbone model, using the [google drive link](https://drive.google.com/file/d/1L_ESw_ndOwSYChE3nw1zN1Hjy5ohSN80/view?usp=drive_link), but it requires permission. Is it possible to change the access type of the file, since I guess many others would like to get them as well?

Best,
Arthur

**Comment by fisheggg** [comment]
By the way, other google drive links seem to be fine, the backbone checkpoint is the only one that requires permission.

**Comment by haoyi-duan** [comment]
Thank you for the reminder. I have already changed the file's access type.
