### ISSUE TITLE
How to get pre-trained weights of grounding module

### ISSUE THREAD

**Issue by kaiw7** [haoyi-duan/DG-SCT#6]
Hi, could I know how you get the pre-trained weights of grounding module? I found you use the different pre-trained weights from LAVISH. Do you use another dataset to pre-trained the whole model to get the pre-trained ground module? If yes, which dataset you use for this pre-training? Many thanks.

**Comment by haoyi-duan** [comment]
We use AVQA dataset to train the grounding module. You can check the [code](https://github.com/haoyi-duan/DG-SCT/tree/main/DG-SCT/AVQA/grounding_gen) for detail.
