### ISSUE TITLE
channel-spatial-temporal prompt

### ISSUE THREAD

**Issue by yujialele** [haoyi-duan/DG-SCT#7]
Thank you for your good work! I recently have read your code and generated some questions. I find that channel-spatial cross-attention module is projected into multi-head attention and the FFN in each Swin-transformer blocks, but temporal prompt is only used in the last Swin-transformer block. This is not quite consistent with the text description in your paper.

**Comment by haoyi-duan** [comment]
Thank you for your interest in our work and for taking the time to read our paper and code so carefully!

You brought up a great point regarding the implementation of the temporal-gated attention in our Swin-transformer blocks. As mentioned in Section 3.3 of our paper, under the subsection "Temporal-gated attention," we indeed add this mechanism specifically in the final layer of the transformer.

The decision to integrate the temporal-gated attention only at the last stage was driven by our intention to balance computational efficiency and performance enhancement. We found that applying this mechanism in the final layer alone is sufficient to capture the necessary temporal dynamics without significantly increasing the computational burden across all layers.

We appreciate your feedback as it helps us improve our work and communications!
